chore(build): Add meson to the build pipeline
arxlang/arxcpp pull request #40
Opened 2022-07-15 20:47 UTC by xmnlab

# PR Checklist

Ensure that:

- [ ] it includes tests.
- [ ] the tests for your implementation are executed on CI.
- [ ] it includes documentation
- [ ] the PR's title is according to the [semantic-release pattern][semantic-release-message].
  - `chore:` is used for CI, test, support tasks or any other task that is not user facing task.
  - `feat:` is used for a new feature or when a existent one is improved.
  - `fix:` is used when a bug is fixed.
  - `breaking change:` is used when there is a compability break.
- [ ] pre-commit hooks were executed locally

[semantic-release-message]: https://github.com/semantic-release/semantic-release/blob/master/README.md#commit-message-format "Semantic Release Commit Message Format"

2022-07-15 23:00 UTC, eli-schwartz requested changes

2022-07-15 23:00 UTC, eli-schwartz commented on meson.build
> +  deps += [dependency('gtest')]
I would instead use:

```suggestion
gtest_dep = dependency('gtest', required: get_option('tests'))
if gtest_dep.found()
    deps += [gtest_dep]
```

The point of a feature option is to be a tristate option. If:
- enabled, then that's equivalent to default "required: true".
- disabled, then the dependency logs as "skipped: feature **tests** is disabled"
- auto, then that's equivalent to "required: false"

So, the effect is identical to what you currently did, except that in the auto case it will try to find gtest, and only enable the tests if gtest is found.

2022-07-16 02:19 UTC, xmnlab commented on meson.build
> +  deps += [dependency('gtest')]
That looks very nice. Thanks for the review :) I will apply your suggestion soon!! Thanks

2022-08-02 20:19 UTC, xmnlab commented
I am back here ... sorry for the delay. I had some personal issues last weeks. let's move this forward :)

2022-08-08 18:56 UTC, xmnlab commented
it seems that the compile_commands.json file generated by meson is different than the one generated by cmake.
for now I am just copying the one from cmake and use it with clang-tidy.

I will open an issue so we can resolved that later

2022-08-08 19:16 UTC, eli-schwartz commented
This is just about the use of `-pipe` breaking clang-tidy?

2022-08-09 23:00 UTC, xmnlab commented
> This is just about the use of `-pipe` breaking clang-tidy?

removing that didn't resolve the problem .. not sure yet why it is happening

2022-08-10 21:11 UTC, merged

2022-08-10 21:12 UTC, xmnlab commented
thanks @eli-schwartz for your review and comments