docs: Doxygen
arxlang/arxcpp pull request #57
Opened 2022-09-24 00:02 UTC by luabida

Adding docstring to classes and methods.
fix #29 partially

# PR Checklist

Ensure that:

- [ ] it includes tests.
- [ ] the tests for your implementation are executed on CI.
- [x] it includes documentation
- [x] the PR's title is according to the [semantic-release pattern][semantic-release-message].
  - `build`: Changes that affect the build system or external dependencies (example scopes: cmake, meson, etc)
  - `ci`: Changes to our CI configuration files and scripts (examples: CircleCi, SauceLabs)
  - `docs`: Documentation only changes
  - `perf`: A code change that improves performance
  - `refactor`: A code change that neither fixes a bug nor adds a feature
  - `test`: Adding missing tests or correcting existing tests
  - `chore:` Can be used as a generic task for tasks such as CI, test, support tasks or any other task that is not user facing task.
  - `feat:` is used for a new feature or when a existent one is improved.
  - `fix:` is used when a bug is fixed.
  - `breaking change:` is used when there is a compability break.
- [x] pre-commit hooks were executed locally

[semantic-release-message]: https://github.com/semantic-release/semantic-release/blob/master/README.md#commit-message-format "Semantic Release Commit Message Format"

2022-09-26 21:49 UTC, xmnlab commented on arx/src/parser.cpp
> +  /** The step value is optional. */
I think that for the regular comments it is ok to keep it with `//`
any reason for changing that?

PS: there are a lot of other situations like this. I am just commenting in this one

2022-09-26 21:51 UTC, xmnlab commented on docs/templates/example_test.cpp
> +/**
do we really need this example file?

2022-09-26 22:01 UTC, xmnlab commented on arx/src/codegen.cpp
> +*note : arrow will not be used yet * #include<arrow / api.h> *
can you move back to the original structure please?

2022-09-26 22:02 UTC, xmnlab commented on arx/src/codegen.cpp
> +    extern std::map<char, int> BinopPrecedence;
could you remove this extra space?

2022-09-26 22:02 UTC, xmnlab commented on arx/src/codegen.cpp
> +/**
can you keep regular comments with `//` please?

2022-09-26 22:13 UTC, xmnlab requested changes
thanks for working on that @luabida !

just a few comments:

- please keep regular comments with `//`
- check if no cpp/h files includes were not changed
- you can remove the test file for the documentation that I mentioned in a comment inline
- check if no regular code was changed (as the includes I mentioned above)


how can I test it locally?

I think that a normal workflow for testing would be:
- run make docs-build
- in another terminal, run make docs-api

2022-09-27 12:05 UTC, luabida commented on arx/src/parser.cpp
> +  /** The step value is optional. */
Thanks for the review! Ok, I'll change it back

2022-09-28 13:15 UTC, luabida commented
I've changed back the comments mentioned and solved some warnings from Doxygen.
To test the API Docs, first urn `make docs-api` and access with a browser the html page located at `{...}/arx/build/api/index.html`

2022-09-29 15:12 UTC, xmnlab commented
https://github.com/arxlang/arx/actions/runs/3143836541/jobs/5109060932#step:8:1

@luabida the lint step is failing .. do you mind fix that ?
you can use `pre-commit run --all-files --verbose`

2022-09-29 17:33 UTC, luabida commented
> @luabida the lint step is failing .. do you mind fix that ? you can use `pre-commit run --all-files --verbose`

sorry for that, I've run lint but forgot to push it. Yet, the lint is still failing to me, maybe you can catch the error.

2022-09-29 22:05 UTC, xmnlab approved these changes
LGTM! thanks for working on that!

2022-09-29 22:05 UTC, merged